
version: "3.9"
services:
  sensor-service:
    image: svenschmidt1502/rpi4-temperatures-humidity
    container_name: dht22_sensor_service
    restart: always
    privileged: true  # Benötigt für GPIO-Zugriff auf Raspberry Pi
    environment:
      - BROKER_IP=${BROKER_IP}
      - BROKER_PORT=${BROKER_PORT}
      - TOPIC_TEMPERATURES=${TOPIC_TEMPERATURES}
      - TOPIC_HUMIDITY=${TOPIC_HUMIDITY}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
    devices:
      - "/dev/:/dev/"  # Zugriff auf GPIO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

